Add manpage

diff --git a/bin/rmkeep b/bin/rmkeep
--- a/bin/rmkeep
+++ b/bin/rmkeep
@@ -13,7 +13,7 @@ cat << EOF
 Usage: rmkeep [options] <pattern>
 
 OPTIONS:
-   -p <path>    Change working directory
+   -p <path>    Change directory (default: current working directory)
    -k <number>  Files to keep (default: 0 = all)
    -r           Reverse sort
    -n           Dry run
@@ -22,7 +22,7 @@ OPTIONS:
 EOF
 }
 
-
+#
 set -e
 
 # Initialization
@@ -58,37 +58,41 @@ if [ $VERBOSE -eq 1 ]
 then
     echo
     printf "This is RMKEEP, keep and remove filenames matching a regex pattern\n"
-    printf "Last modified 2021/04/11\n\n"
+    printf "Last modified 2021/11/04\n\n"
+fi
+
+# Check number of files to keep
+if [ "$KEEP" -lt 0 ]
+then
+    echo "Invalid number of files"
+    usage
+    exit 1
+fi
+
+# Check if directory exists
+if [ ! -d "$DIR" ]
+then
+    echo "Cannot change to $DIR"
+    usage
+    exit 1
 fi
 
 # Skip options and shift index
 shift $((OPTIND-1))
 
 # Check number of parameters
-if [ $# -ne 1 ]
+if [ $# -gt 1 ]
 then
-    echo "Illegal number of parameters"
+    echo "Invalid number of parameters"
     usage
     exit 1
-fi
-
-# Check number of files to keep
-if [ "${KEEP}" -lt 0 ]
+elif [ $# -eq 1 ]
 then
-    echo "Illegal number of files"
-    usage
-    exit 1
-fi
-
-# Get arguments
-REGEX=$1
-
-# Check if directory exists
-if [ ! -d "${DIR}" ]
-then
-    echo "Cannot change to ${DIR}"
-    usage
-    exit 1
+    # Get argument
+    REGEX=$1
+else
+    # No regex
+    REGEX=
 fi
 
 # Change to working directory
@@ -101,7 +105,10 @@ TEMPNAME=$(mktemp -t "$(basename "$0")-XXXXXX")
 for f in $(find . -maxdepth 1 -type f | sort ${REVERSE})
 do
     fname=$(basename "${f}")
-    [[ ${fname} =~ ${REGEX} ]] && echo "${fname}" >> "${TEMPNAME}"
+    if [ -z "$REGEX" ] || [[ ${fname} =~ ${REGEX} ]]
+    then
+        echo "${fname}" >> "${TEMPNAME}"
+    fi
 done
 
 # Get number of matches
